export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header style={{
        backgroundColor: 'lightblue',
        padding: '10px',
      }}>
        <p>Header</p>
      </header>
      
      {children}
      
      <footer style={{
        backgroundColor: 'lightblue',
        padding: '10px',
      }}>
        <p>Footer</p>
      </footer>
      </body>
    </html>
  )
}
